#!/bin/bash
#
# Read an hdf5 file and outputs an .rst file with a description
# of its groups/datasets
#
# ICRAR - International Centre for Radio Astronomy Research
# (c) UWA - The University of Western Australia, 2017
# Copyright by UWA (in the framework of the ICRAR)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

if [ $# -lt 1 ]; then
	echo "Usage: $0 <hdf5_file>"
	exit 1
fi

sed_cmd='
# Skip the root group
/.*GROUP "\/"/ d

# For each group name print its name enclosed in `` quotes
# and underline it with ^ characters
/.*GROUP "[^\/.]*/ {
  h
  s/.*GROUP "\(.*\)".*/\
\
``\1``/
  p
  x
  s/.*GROUP "\(.*\)".*/\1/
  s/./^/g
  s/.*/^^&^^/g
  p
}

# For each dataset, print a list item with the dataset name
# enclosed in `` quotes and the comment in normal characters
/.*DATASET ".*/ {
  $ !{
    N
    s/.*DATASET "\(.*\)" {\n.*COMMENT "\(.*\)"/* ``\1``: \2/
    p
  }
}'

cat <<EOF
.. This file has been automatically generated by the properties_as_list.sh
   utility found under the scripts/ directory of the shark repository.
   ======================
   DO NOT MODIFY MANUALLY
   ======================
   Please see the script's help for more information on how to use it
EOF
h5dump -H "$1" | sed -n "$sed_cmd"
